[package]
name = "configuru"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonc-parser = { version = "0.21.1", features = ["serde"] }
serde_json = "1.0.96"
